config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :photos, only: [:destroy]
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :events, except: [:destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :events do
    resources :registrations, only: [:create]
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :photos
  has_many :registrations, dependent: :destroy
  has_many :participants, source: :user, through: :registrations


  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500}

  def bargain?
    price < 10
  end

  def self.order_by_price
    order('price asc')
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord

  validates :first_name, :last_name, :bio,
            presence: true

  def full_name
    first_name + " " +  last_name
  end

  def self.by_initial(letter)
  where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event


def price
  @price = event.price
end 

  # validates :maximum_guests_count
  #
  # def maximum_guests_count
  #   if guests_count > 3
  #     errors.add(:guests_count, ": One person can at most register for 3 guests.")
  #   end
  # end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy
  has_one :profile
  has_many :registrations, dependent: :destroy
  has_many :registered_events, through: :registrations, source: :event




  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
   end

  def new
    @categories = Category.all
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      images_params.each do |image|
        @event.photos.create(image: image)
      end
      redirect_to @event, notice: "Event created"
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path,
      notice: "You don't have permission."
    end
  end

  def update
    if @event.update(event_params)
      images_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to @event, notice: "Event successfully updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def images_params
    params[:images].present? ? params.require(:images) : []
  end


  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :capacity,
    :includes_food, :includes_drinks, :starts_at, :ends_at, :active, category_ids: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
    <%= yield %>

    <hr />
    <p>&copy; 2017 Jiamei Wu</p>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<head>
<link rel="stylesheet" href="homepage.scss" type="text/css">

<style>

body {
  background.image: url(<%=asset_path"https://res.cloudinary.com/supermay/image/upload/t_media_lib_thumb/v1499413678/background_rjwn9d.jpg"%>);
}
</style>
</head>


<body>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <h1><center>&#10084;This is the Home of Funny Events.&#10084;</center></h1>

        </div>
        <div class="item">
            <h1><center>Ok, maybe you are right. Don't always have to be funny.</center></h1>
        </div>
        <div class="item">
            <h1><center>The most important is that you enjoy it!!!&#10084;</center></h1>
        </div>

      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </body>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurup", root_path, class: "navbar-brand" %>
    </div>



    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Your Events", events_path %></li>
            <li role="separator" class="divider"></li>

            <% if current_user.has_profile? %>
              <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
            <% else %>
              <li><%= link_to "Create Profile", new_profile_path %></li>
            <% end %>
            <li><%= link_to "Edit Password", edit_user_registration_path %></li>

            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>

        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>