config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :photos, only: [:destroy]
  root to: 'pages#home'

  devise_for :users

  resources :users, only: [:show]
  resources :events, except: [:destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :events do
    resources :registrations, only: [:create]
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :photos
  has_many :registrations, dependent: :destroy
  has_many :participants, source: :user, through: :registrations


  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500}

  def bargain?
    price < 10
  end

  def self.order_by_price
    order('price asc')
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord

  validates :first_name, :last_name, :bio,
            presence: true

  def full_name
    first_name + " " +  last_name
  end

  def self.by_initial(letter)
  where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end

end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event


def price
  @price = event.price
end 

  # validates :maximum_guests_count
  #
  # def maximum_guests_count
  #   if guests_count > 3
  #     errors.add(:guests_count, ": One person can at most register for 3 guests.")
  #   end
  # end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy
  has_one :profile
  has_many :registrations, dependent: :destroy
  has_many :registered_events, through: :registrations, source: :event




  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
   end

  def new
    @categories = Category.all
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      images_params.each do |image|
        @event.photos.create(image: image)
      end
      redirect_to @event, notice: "Event created"
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path,
      notice: "You don't have permission."
    end
  end

  def update
    if @event.update(event_params)
      images_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to @event, notice: "Event successfully updated"
    else
      render :edit
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def images_params
    params[:images].present? ? params.require(:images) : []
  end


  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :capacity,
    :includes_food, :includes_drinks, :starts_at, :ends_at, :active, category_ids: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event.id),
      notice: "Photos successfully removed!"
    else
      redirect_to @event, notice: "Cannot delete that photo."
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_profile, only: [:edit, :update]
    before_action :authenticate_user!

    def new
      @profile = Profile.new
    end

    def create
      @profile = current_user.build_profile(profile_params)

      if @profile.save
        redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
      else
        render :edit
      end
    end

    private
      def set_profile
        @profile = current_user.profile
      end

      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :bio)
      end
  end

app/controllers/types_controller.rb
class TypesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: {multipart: true}  do |f| %>
  <div class="form-group">
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Description</label>
      <%= f.text_field :description, placeholder: "Description", class: "form-control" %>
    </div>


    <div class="form-group">
      <label>Location</label>
      <%= f.text_field :location, placeholder: "Location", class: "form-control" %>
    </div>


    <div class="form-group">
      <label>Capacity</label>
      <%= f.select :capacity, [["Up to 10", 10], ["10 to 20", 20], ["20 to 50", 50], ["50 to 100", 100]], prompt: "Select capacity of the event", class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Price</label>
      <%= f.number_field :price, plceholder: "price in euro", class: "form-control" %>
    </div>

  <div class="form-group">
    <%= f.check_box :includes_food %> Include Food
  </div>
  <div class="form-group">
    <%= f.check_box :includes_drinks %> Include Drinks
  </div>

  <div class="form-group">
    Start Time <%= f.datetime_field :starts_at %>
  </div>

  <div class="form-group">
    End Time <%= f.datetime_field :ends_at %>
  </div>


  <label>Categories of This Event</label>

    <%= f.collection_check_boxes(:category_ids, @categories, :id, :name) do |b| %>
    <div class="form-group">
      <%= b.check_box(class: "check_box") %> <%= b.object.name %>
    </div>
  <% end %>

<label>Photos</label>
<div id="photos">
  <%= render 'photos/list' %>
</div>

  <div class="form-group">
    Update Photos
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </div>




  <label>Create this Event?</label>

  <div class="form-group">
    <%= f.check_box :active %> Yes
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit Event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Events", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Registrations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your events
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create new event?
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<% if current_user != @event.user %>
  <div class="panel panel-primary">
    <div class="panel-heading">Book this event</div>

    <div class="panel-body">
      <%= render 'registrations/form' %>
    </div>
  </div>
<% end %>

<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <p>location: <%= @event.location %></p>


    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Price per Person: <%= @event.price %></p>
    <p>Capacity: <%= @event.capacity %></p>

    <!-- About -->
    <h4>About</h4>
    <p>Descriiption: <%= @event.description %></p>
    <p>Start at:<%= @event.starts_at %></p>
    <p>End at:<%= @event.ends_at %></p>


    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<s>Includes Food</s>").html_safe : "Includes Food" %></li>
      <li><%= !@event.includes_drinks ? ("<del>includes_drinks</del>").html_safe : "Includes Drinks" %></li>
    </ul>

    <h4>Categories</h4>
    <% @categories.each do |category| %>
      <span class="label label-success"><%= category.name %></span>
    <% end %>


    <h4>Photos</h4>
    <% @photos.each do |photo| %>
      <%= image_tag photo.image.thumbnail  %>
    <% end  %>

  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <span class="btn btn-default">
          <%= link_to "Delete", photo_path(photo.id), class: "btn btn-default",
          method: :delete, data: {confirm: "Are you sure?"}  %>
        </span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>